.PHONY: help install build-ui build-docker up down logs lint test clean migrate

.DEFAULT_GOAL := help

help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

## --- Installation & Setup ---

install: ## Install Python and frontend dependencies
	@echo "Installing Python dependencies..."
	uv sync
	@echo "Installing frontend dependencies..."
	cd frontend && npm ci
	@echo "Installing pre-commit hooks..."
	uv run pre-commit install

## --- Build ---

build-ui: ## Build the Vue.js frontend for production
	cd frontend && npm run build

build-ui-deploy: ## Build frontend and hot-deploy into running web container
	cd frontend && npm run build && docker cp dist/. echo_dsrn_graph_web:/app/frontend/dist/ && docker restart echo_dsrn_graph_web

build-docker: ## Build the Docker image (set HF_TOKEN in .env for gated model access)
	docker compose build

## --- Run ---

up: ## Start the system with Docker Compose
	docker compose up -d
	@echo "App running at http://localhost:7860"

down: ## Stop and remove all containers
	docker compose down

logs: ## View logs from all containers
	docker compose logs

logs-f: ## Follow logs from all containers
	docker compose logs -f

## --- Quality ---

lint: ## Run all pre-commit hooks
	uv run pre-commit run --all-files

lint-fix: ## Run Ruff linter with auto-fix
	uv run ruff check --fix .

lint-ui: ## Run Prettier on frontend source
	cd frontend && npx --yes prettier --write "src/**/*.{vue,js,css}"

## --- Test ---

test: ## Run Python unit tests
	uv run pytest tests/ -v

test-cov: ## Run tests with coverage report
	uv run pytest tests/ -v --cov=backend --cov-report=term-missing

## --- Database ---

migrate: ## Run Alembic migrations (local SQLite)
	uv run alembic -c backend/alembic.ini upgrade head

migration-gen: ## Generate an autogenerated Alembic migration (Usage: make migration-gen MSG="description")
	uv run alembic -c backend/alembic.ini revision --autogenerate -m "$(MSG)"

## --- LLM-as-Judge ---

judge: ## Run LLM-as-Judge batch — sync (Usage: make judge N=100)
	./scripts/run_judges.sh $(or $(N),100)

judge-async: ## Dispatch async LLM-as-Judge tasks to Celery worker (Usage: make judge-async N=100)
	cd backend && uv run python judge_cli.py --source catalog --n $(or $(N),100) --async

judge-async-arxiv: ## Dispatch async judge tasks for arXiv papers
	cd backend && uv run python judge_cli.py --source arxiv --n $(or $(N),50) --async

judge-async-openaire: ## Dispatch async judge tasks for OpenAIRE papers
	cd backend && uv run python judge_cli.py --source openaire --n $(or $(N),50) --async

judge-eval: ## Generate LLM-as-Judge evaluation report
	uv run python backend/judge_eval.py

## --- Documentation ---

docs-serve: ## Serve MkDocs documentation locally (http://localhost:8000)
	uv run mkdocs serve

docs-build: ## Build MkDocs static site into site/
	uv run mkdocs build

## --- Maintenance ---

clean: ## Remove Python cache and build artifacts
	find . -type d -name "__pycache__" -exec rm -rf {} +
	rm -rf .venv
	rm -rf frontend/node_modules
	rm -rf frontend/dist
	rm -rf .pytest_cache .ruff_cache

clean-docker: ## Wipe all project containers, volumes, and images
	docker compose down -v --remove-orphans
	@echo "Docker environment cleaned."

reset-db: ## Delete and recreate the SQLite database
	rm -f data/collaborative.db data/collaborative.db-shm data/collaborative.db-wal
	uv run alembic -c backend/alembic.ini upgrade head
	@echo "Database reset complete."
