"""initial_schema_with_llm_judge

Revision ID: 2d6a8f810146
Revises:
Create Date: 2026-06-12 21:45:14.418858

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d6a8f810146"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_records",
        sa.Column("doi", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("abstract", sa.String(), nullable=False),
        sa.Column("initial_intent", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("doi"),
    )
    op.create_index(
        op.f("ix_paper_records_doi"), "paper_records", ["doi"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("institution", sa.String(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "annotations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_doi", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("llm_model", sa.String(), nullable=True),
        sa.Column("annotator_type", sa.String(), nullable=False),
        sa.Column("proposed_label", sa.String(), nullable=True),
        sa.Column("is_flagged", sa.Boolean(), nullable=True),
        sa.Column("flag_reason", sa.String(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "(user_id IS NOT NULL AND llm_model IS NULL) OR (user_id IS NULL AND llm_model IS NOT NULL)",
            name="ck_annotation_single_annotator",
        ),
        sa.ForeignKeyConstraint(
            ["paper_doi"], ["paper_records.doi"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_doi", "llm_model", name="uq_annotation_llm"),
        sa.UniqueConstraint("paper_doi", "user_id", name="uq_annotation_human"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("annotations")
    op.drop_table("users")
    op.drop_index(op.f("ix_paper_records_doi"), table_name="paper_records")
    op.drop_table("paper_records")
    # ### end Alembic commands ###
