"""add model_version rounds

Revision ID: 38d19790309c
Revises: 3a7f8c9d1e2b
Create Date: 2026-08-14 15:22:56.843696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d19790309c'
down_revision: Union[str, Sequence[str], None] = '3a7f8c9d1e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Round that produced all pre-versioning rows (papers + annotations).
LEGACY_ROUND = 'v0.1.3'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('model_version', sa.String(), nullable=True))
    op.create_index(op.f('ix_annotations_model_version'), 'annotations', ['model_version'], unique=False)
    op.add_column('paper_records', sa.Column('model_version', sa.String(), nullable=True))
    op.create_index(op.f('ix_paper_records_model_version'), 'paper_records', ['model_version'], unique=False)
    # ### end Alembic commands ###

    # Backfill: everything in the DB today was collected during the v0.1.3 round.
    conn = op.get_bind()
    conn.execute(
        sa.text('UPDATE paper_records SET model_version = :v WHERE model_version IS NULL'),
        {'v': LEGACY_ROUND},
    )
    conn.execute(
        sa.text('UPDATE annotations SET model_version = :v WHERE model_version IS NULL'),
        {'v': LEGACY_ROUND},
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_records_model_version'), table_name='paper_records')
    op.drop_column('paper_records', 'model_version')
    op.drop_index(op.f('ix_annotations_model_version'), table_name='annotations')
    op.drop_column('annotations', 'model_version')
    # ### end Alembic commands ###
