"""add join and sort indexes for hub queries

Revision ID: 446d1c1f2aaf
Revises: 38d19790309c
Create Date: 2026-08-14 23:55:39.988252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446d1c1f2aaf'
down_revision: Union[str, Sequence[str], None] = '38d19790309c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_annotations_paper_doi_version', 'annotations', ['paper_doi', 'model_version'], unique=False)
    op.create_index(op.f('ix_paper_records_created_at'), 'paper_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_records_source'), 'paper_records', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_records_source'), table_name='paper_records')
    op.drop_index(op.f('ix_paper_records_created_at'), table_name='paper_records')
    op.drop_index('ix_annotations_paper_doi_version', table_name='annotations')
    # ### end Alembic commands ###
