apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels: {{ include "chart.labels" . | nindent 4 }}
data:
  APP_BASE_URL: {{ .Values.config.appBaseUrl | quote }}
  APP_PORT: {{ .Values.config.appPort | quote }}
  LLM_BASE_URL: {{ .Values.config.llmBaseUrl | quote }}
  LLM_API_KEY: {{ .Values.config.llmApiKey | quote }}
  HF_DATASETS_URL: {{ .Values.config.hfDatasetsUrl | quote }}
  HUB_READ_ONLY: {{ ternary "true" "false" .Values.config.hubReadOnly | quote }}
  MODEL_VERSION: {{ .Values.config.modelVersion | quote }}
  REDIS_URL: {{ if .Values.redis.externalUrl }}{{ .Values.redis.externalUrl | quote }}{{ else }}"redis://{{ include "chart.fullname" . }}-redis:6379/0"{{ end }}
