apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-worker
  labels: {{ include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVICE_TYPE
              value: worker-cpu
            - name: CONCURRENCY
              value: {{ .Values.worker.concurrency | quote }}
            - name: DATABASE_URL
              value: "postgresql+psycopg2://postgres:$(POSTGRES_PASSWORD)@{{ include "chart.fullname" . }}-postgres:5432/echo_dsrn"
          envFrom:
            - configMapRef:
                name: {{ include "chart.fullname" . }}-config
            - secretRef:
                name: {{ include "chart.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
