apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secrets
  labels: {{ include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  HF_TOKEN: {{ .Values.secrets.hfToken | quote }}
  HF_CLIENT_ID: {{ .Values.secrets.hfClientId | quote }}
  HF_CLIENT_SECRET: {{ .Values.secrets.hfClientSecret | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  MCP_API_KEY: {{ .Values.secrets.mcpApiKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
